#!/bin/bash



#####################################
# Author: Pratik
# Date : 15/01/2025
#
# Version: V1
#
# This cript will report the aws resource usage
####################################



# AWS S3
# AWS EC2
# AWS lambda
# AWS IAM Users

set -x

# list s3 buckets
echo "print list of s3 buckets"
aws s3 ls

# list EC2 instance
echo "print list of EC2 instances"
aws ec2 describe-instances

# list lambda
echo "describe list of lambda function"
aws lambda list-functions

# list IAM users
echo "describe list of IAM users"
aws iam list-users
