#!/bin/bash




#########################################
#
# Auther : Pratik
# Date : 09/01/2025
# version : V1
#
# Script to print number of 'S' in mississippi
#
# #########################################





x=mississippi


grep -o "s"  <<<"$x" | wc -l
