#!/bin/bash




#########################
# Auther : Pratik
# Date : 09/01/2025
# Version : V1

# This is a script to print numbers divided by 3 & 5 and not 15
#########################


# Divisible by 3, divisible by 5, not 3*5=15

for i in {1..100}; do

if ([ `expr $i % 3` == 0 ] || [ `expr $i % 5` == 0 ]) && [ `expr $i % 15` != 0 ];

then
        echo $i

fi
done
