#!/bin/bash

###################
# Author: Pratik
# Date: 06/01/2025
#
# This Script outputs the node health
#
#
# version: V1
##################


set -x #debug mode
set -e # exit the script when there is a error
set -o pipefail

df -h

free -g

nproc

ps -ef | grep amazon | awk -F" " '{print $2}'
